clean: true
author: Joshua Emmons
author_url: https://uptake.com
github_url: https://github.com/UptakeMobile/uptake-toolbox-ios
module: UptakeToolbox
root_url: http://mobile-toolkit-docs.services.common.int.uptake.com/docs/uptake-toolbox-ios/

custom_categories:
  - name: Helpers
    children:
    - ErrorHelper
    - ErrorMatcher
  - name: Factories
    children: 
    - Logging
    
